Backend
edwardgreenwood38/Checkmate pull request #12
Opened 2024-03-29 01:44 UTC by M4RKL4B0Y

Updated config file, added a lists_controller.js and updated tasks_controller.js

2024-03-29 01:46 UTC, tan-man21 commented on server/controllers/lists_controller.js
> +const { Lists } = db
Lists will need to be changed to "List
 singular like tasks.

2024-03-29 01:49 UTC, tan-man21 requested changes
In lists controller Lists needs to be changed to be singular List

2024-03-29 01:58 UTC, M4RKL4B0Y reviewed
Good eye, Thanks Tan-Man

2024-03-29 01:59 UTC, tan-man21 approved these changes
Looks great!!

2024-04-02 22:27 UTC, edwardgreenwood38 reviewed
I only see one migration to add the 'Task' table.  are you still working on the 'List' table?

2024-04-02 22:33 UTC, M4RKL4B0Y commented
The lists table is within Tanner's branch. He tackled tables while I handled controllers.

2024-04-02 22:34 UTC, edwardgreenwood38 approved these changes
code looks good. will wait on Tanners merge to get the other items.

2024-04-02 22:34 UTC, merged

2024-04-02 22:34 UTC, M4RKL4B0Y commented
Thank you sir!